### ISSUE TITLE
Rewrite in C++

### ISSUE THREAD

**Issue by JCWasmx86** [JCWasmx86/Swift-MesonLSP#28]
Using Swift was a cool idea, but it causes a lot of problems:

- DX: Basically no tooling for Linux, small ecosystem for Linux, basically no community outside of Apple-Dev/Serverside.
- Distribution: Huge binaries due to stdlib/Foundation
- Performance: No LTO etc. possible outside of Apple OSs

This can be solved by C++:
- DX: Huge community, great tools, excellent ecosystem
- Distribution: Basically trivial due to a lot of other programs using C++ on Linux
- Performance: LTO/PGO possible, manual memory usage

Changes:
```
Rust-MesonLSP --lsp [--stdio] # For starting language server
Rust-MesonLSP meson.build # For linting
Rust-MesonLSP meson.build --test # For testing using the testing framework
Rust-MesonLSP --wrap a.wrap b.wrap --wrap-output wo --wrap-package-files ./package-files/ # For downloading wrap files
```

## Libraries to use:
- libcurl for downloading files
- libarchive for extracting tar.{xz,gz,bz2} and zip files
- [tree_sitter](https://docs.rs/tree-sitter/latest/tree_sitter/) for tree-sitter
- ??? for SHA256
- libuuid for generating uuids
- ??? for hg-wraps (Or just spawn hg?)
- ??? for svn-wraps (Or just spawn svn?)

**Comment by JCWasmx86** [comment]
The most difficult aspect will be the representation of nodes etc. Currently it is quite inheritance heavy, but Rust sadly doesn't have any inheritance.

TBD

**Comment by JCWasmx86** [comment]
The alternative would be using C++ as I don't have to remodel my objects and design.

**Comment by JCWasmx86** [comment]
Basic exploration of Rust concepts has shown, that the design would differ a lot due to missing inheritance in Rust🙄. Maybe going back to Vala would be a smarter idea?

Pros:
- Sane OOP possible
- Sane buildsystem can be used

Cons:
- Unsafe code
- Less expressive (Currently: ~18kLOC, expected after possible Vala-rewrite: 30-35kLOC)

Completely weird idea: Ada?

**Comment by JCWasmx86** [comment]
After playing a bit more with C++, I would rather go with C++.

Pros:
- Sane OOP
- Sane buildsystem
- Native code
- Not a niche language like Swift

Cons:
- Complex language
- Memory unsafe
- Dependencies especially on Windows will be awful.

Mitigating the cons:
- Complex language: Limit to the most recent GNUC++23
- Memory unsafe: Extensive test coverage, valgrind/ubsan/asan, clang-tidy, `gcc -fanalyzer`
- Dependency management: Static linking as much as possible

I'm not sure what it will mean for the supported OSs:
- Windows: No MSVC support, if it works: great, if it doesn't: I don't care. Use clang/gcc. Dependencies will be statically linked or added as DLLs
- MacOS: Should be easy
- Linux:
  - Binaries for e.g. vim or vscode-meson: Statically linked as far as possible (Maybe even stdc++) to ensure maximum compatibility even with ancient OSs like Ubuntu 18.04
  - Distro packages: If there is a compiler that can compile C++23, it will be supported. Maximum amount of dynamic linking. Fedora COPRs will be 38+ only (=> Fedora 37 dropped), Ubuntu probably 22.04 only. (Maybe I should add debs for 22.10, 23.04 etc, too). Debian: TBD

**Comment by JCWasmx86** [comment]
The tool will be split up into two different executables:

- A meson linter, e.g. for CI (Executable name: TBD, should be something similar to meson/boson/muon)
- The language server. This executable will still take the same CLI arguments as the current Swift-MesonLSP, but they won't be changed/user-friendly. (Executable name: Swift-MesonLSP)

**Comment by JCWasmx86** [comment]
# Dependencies:

- g++ (13, maybe 12) or clang++ (17, maybe 16)
- tree-sitter
- tree-sitter-meson
- tree-sitter-ini
- https://github.com/amosnier/sha-2
- nlohmann_json
- libcurl
- libarchive
- libuuid for tests

# Distributions:
- vscode-meson:
  - MacOS: ARM/X86 both should work as I don't use any weird dependencies.
  - Linux
  - Windows
- COPR
  - Fedora 38 (If it compiles)
  - Fedora 39
  - Fedora 40/Rawhide
- APT-Repo
 - All the ubuntu versions that have a somewhat new-ish C++ compiler
 - All the debian versions that have a somewhat new-ish C++ compiler
- AUR: Won't be a problem, because Arch doesn't has ancient C++ compilers
- Flatpak: ["I do wish we had a way to either bundle a meson LSP or make it an SDK extension/etc"](https://gitlab.gnome.org/GNOME/gnome-builder/-/merge_requests/743#note_1797368)

For the vscode-meson extension, everything should be linked statically as far as possible. Furthermore on Linux we have to check it's somewhat compatible with older versions. [The website](https://code.visualstudio.com/Docs/supporting/requirements#_platforms) lists that VSCode supports these platforms:

- Windows 10 and 11 (64-bit)
- macOS [...]
- Linux (Debian): Ubuntu Desktop 18.04, Debian 10
- Linux (Red Hat): Red Hat Enterprise Linux 7, CentOS 7, Fedora 35

I hope that it is possible to link everything except libcurl statically (As it seems to be unsupported and after more thoughts I don't want to bring in e.g. tinycurl)

The distribution specific things will be linked dynamically to the dependencies to reduce the footprint.


Flatpak won't be any problem as it has the most recent stuff possible

**Comment by JCWasmx86** [comment]
Statically linking in an alpine container is possible => Ubuntu 18.04 won't be a problem anymore

**Comment by eli-schwartz** [comment]
> ??? for SHA256

Is there a specific reason not to simply use openssl's libcrypto?

> * ??? for hg-wraps (Or just spawn hg?)
> 
> * ??? for svn-wraps (Or just spawn svn?)

Meson spawns git / hg / svn. I guess you could just run `meson subprojects download`? This could handle rather a lot.

**Comment by JCWasmx86** [comment]
> Is there a specific reason not to simply use openssl's libcrypto?

Yes. It's static linking. As soon as a I statically link OpenSSL (E.g. for the vscode-meson extension, as it has to work on basically any somewhat recent distribution), I would have to monitor e.g. security related updates. I'm now using https://github.com/amosnier/sha-2, as it's basically trivial to use. But I will consider adding an OpenSSL support, too for e.g. distribution packages (COPR) as I can do "real" packaging work there.

> Meson spawns git / hg / svn. I guess you could just run meson subprojects download? This could handle rather a lot.
 
I haven't thought of this option before. (Currently I'm just spawning all processes, too)

```
usage: meson subprojects download [-h] [--sourcedir SOURCEDIR] [--types TYPES] [-j NUM_PROCESSES] [--allow-insecure] [subprojects ...]

positional arguments:
  subprojects           List of subprojects (default: all)

options:
  -h, --help            show this help message and exit
  --sourcedir SOURCEDIR
                        Path to source directory
  --types TYPES         Comma-separated list of subproject types. Supported types are: file, git, hg, svn (default: all)
  -j NUM_PROCESSES, --num-processes NUM_PROCESSES
                        How many parallel processes to use (Since 0.59.0).
  --allow-insecure      Allow insecure server connections.
```
The only issue I see here is that I can't set the otuput directory AFAIK as I build up some sort of wrap cache:

(Root directory is ~/.cache/c++-mesonlsp/wrapsWorkspace)
```
> abseil-cpp.wrap
  > 6a342731cf9c69bd17a3ef48e8bca4d35b388345b881b829a907471cd2350fcc-1702973757 // <- sha256(wrapContents)-lastAccessed
> glib.wrap
  > https__download.gnome.org_sources_glib_2.74_glib-2.74.0.tar.xz
  > https__download.gnome.org_sources_glib_2.74_glib-2.74.4.tar.xz
etc.
```
This allows sharing setup wraps (As you can e.g. assume that wraps that reference the same commit hash or use the same file with the same hash have the same contents) It takes into account e.g. patch_directory and diff_files

**Comment by fwcd** [comment]
I agree with most of your points, still it's somewhat saddening to see people give up on cross-platform Swift, since the it's essentially a "chicken-and-egg" problem (people perceive it as an Apple language <-> people only use it on Apple platforms). Having written a medium-sized server-side application in Swift, I agree that the ecosystem is a bit lacking. However

> Basically no tooling for Linux

is a bit unfair, IMO. [SourceKit-LSP](https://github.com/apple/sourcekit-lsp) and the [VSCode Swift extension](https://github.com/swift-server/vscode-swift) have made huge steps forward and really are decent for production usage.
