### ISSUE TITLE
Support run muon with existing muon_fmt.ini

### ISSUE THREAD

**Issue by GreenYun** [JCWasmx86/Swift-MesonLSP#39]
**Is your feature request related to a problem? Please describe.**
I have muon_fmt.ini defined in my working directory, and I would like Swift-MesonLSP run just `muon fmt` instead of passing generated configure file into.

**Describe the solution you'd like**
1. Just call `muon fmt <meson.build>` when formatting.
2. Provide an option to specify an `ini` file.
3. Fallback to the generated configuration.

**Describe alternatives you've considered**
As described above

**Will you write a patch?**
No in recent days.

**Will you maintain it, if you submit a patch?**
If I really have patched it, I may.

**Additional context**
N/A

**Comment by JCWasmx86** [comment]
This is already addressed in the C++-Port (2-3 months until availability for Linux, ??? months for macos/windows)
