### ISSUE TITLE
[Post-RIIC++] Update 3rd-Party packages

### ISSUE THREAD

**Issue by JCWasmx86** [JCWasmx86/Swift-MesonLSP#49]
- Update buildsystem from SPM to meson
- Switch executable name from Swift-MesonLSP to mesonlsp

- [x] Ref: https://github.com/NixOS/nixpkgs/pull/269042
- [x] Ref: https://github.com/ScoopInstaller/Extras/issues/11988
- [x] Ref: https://github.com/mason-org/mason-registry/pull/2840
- [x] Update GNOME Builder (Open MR)
- [x] Update VSCode extension (Open PR)
- [x] Neovim
- [x] mason

**Comment by tristan957** [comment]
Already added to neovim lspconfig, currently working on mason.
